name: Continuous Integration

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.3
        with:
          linter: pylint

  discord-webhook:
    runs-on: ubuntu-latest
    steps:
      # - name: Your previous build steps
    
      - name: Notify discord
        uses: th0th/notify-discord@v0.4.1
        if: ${{ always() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Build and deploy"
          GITHUB_JOB_STATUS: ${{ job.status }}
